name: Test backend and frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  test-data-visualisation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Data Visualisation Tests
        working-directory: ./data-visualisation
        run: |
          python3 -m pip install --upgrade pandas seaborn matplotlib coverage
          coverage run -m unittest test_preparedata.py
          coverage report --fail-under=80

  test-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AI Tests
        working-directory: .
        run: |
          pip3 install -r requirements.txt
          python3 -m unittest test_ai_recommender test_clean_analyse -v

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test Backend
        working-directory: ./backend/
        run: |
          npm ci --include=dev
          npm test
      - name: Test Frontend
        working-directory: ./front-end/
        run: |
          npm ci --include=dev
          npm test
    
