name: Test backend and frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Tests
        working-directory: .
        run: 
          ls

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test Backend
        working-directory: ./backend/
        run: |
          npm ci
          npm test
      - name: Test Frontend
        working-directory: ./front-end/
        run: |
          npm ci
          npm test
    
